
import React, { useState, useEffect } from 'react';
import { Bot, Sparkles, TrendingUp, TrendingDown, AlertTriangle } from 'lucide-react';
import { Market } from '../types';
import { lineraService } from '../services/lineraService';
import { useSound } from './SoundContext';

interface AIAnalystProps {
  market: Market;
}

const AIAnalyst: React.FC<AIAnalystProps> = ({ market }) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isTyping, setIsTyping] = useState(false);
  const [displayedText, setDisplayedText] = useState('');
  const { playPop } = useSound();

  useEffect(() => {
    // Reset when market changes
    setAnalysis(null);
    setDisplayedText('');
    setIsTyping(true);

    const fetchAnalysis = async () => {
        const text = await lineraService.getAIAnalysis(market);
        setAnalysis(text);
    };
    
    // Simulate thinking time
    const timer = setTimeout(fetchAnalysis, 1500);
    return () => clearTimeout(timer);
  }, [market]);

  useEffect(() => {
      if (analysis && isTyping) {
          if (displayedText.length < analysis.length) {
              const timeout = setTimeout(() => {
                  setDisplayedText(analysis.slice(0, displayedText.length + 1));
                  if (Math.random() > 0.8) playPop(); // Subtle typing sound
              }, 20); // Typing speed
              return () => clearTimeout(timeout);
          } else {
              setIsTyping(false);
          }
      }
  }, [analysis, displayedText, isTyping, playPop]);

  if (!analysis && isTyping) {
      return (
          <div className="bg-slate-900 border border-slate-700/50 rounded-xl p-5 shadow-lg relative overflow-hidden">
               <div className="flex items-center gap-2 mb-3">
                   <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400 animate-pulse">
                       <Bot className="w-5 h-5" />
                   </div>
                   <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest animate-pulse">AI Agent Analyzing...</span>
               </div>
               <div className="space-y-2">
                   <div className="h-2 bg-slate-800 rounded w-full animate-pulse"></div>
                   <div className="h-2 bg-slate-800 rounded w-5/6 animate-pulse"></div>
                   <div className="h-2 bg-slate-800 rounded w-4/6 animate-pulse"></div>
               </div>
               {/* Scan line effect */}
               <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-indigo-500/50 to-transparent opacity-50 animate-scan"></div>
          </div>
      );
  }

  return (
    <div className="bg-gradient-to-br from-indigo-950/30 to-slate-900 border border-indigo-500/30 rounded-xl p-6 shadow-[0_0_30px_rgba(99,102,241,0.1)] relative overflow-hidden group">
      <div className="absolute -right-10 -top-10 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl group-hover:bg-indigo-500/20 transition-all"></div>
      
      <div className="flex items-center justify-between mb-4 relative z-10">
          <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white shadow-lg">
                  <Sparkles className="w-4 h-4" />
              </div>
              <div>
                  <h3 className="text-sm font-bold text-white">AI Market Insight</h3>
                  <div className="text-[10px] text-indigo-300">Generated by Cascade LLM-v4</div>
              </div>
          </div>
          {market.outcomes[0].odds > 60 && (
             <div className="px-2 py-1 bg-green-500/10 border border-green-500/30 rounded text-[10px] text-green-400 font-bold uppercase flex items-center gap-1">
                 <TrendingUp className="w-3 h-3" /> High Confidence
             </div>
          )}
      </div>

      <div className="text-sm text-slate-300 leading-relaxed font-mono relative z-10">
          {displayedText}
          {isTyping && <span className="inline-block w-2 h-4 bg-indigo-500 ml-1 animate-pulse align-middle"></span>}
      </div>

      {!isTyping && (
          <div className="mt-4 pt-4 border-t border-indigo-500/20 flex gap-4">
              <div className="flex flex-col">
                  <span className="text-[10px] text-slate-500 uppercase">Volatility Risk</span>
                  <span className="text-xs text-yellow-400 font-bold flex items-center gap-1"><AlertTriangle className="w-3 h-3"/> Moderate</span>
              </div>
              <div className="flex flex-col">
                   <span className="text-[10px] text-slate-500 uppercase">Sentiment</span>
                   <span className="text-xs text-indigo-400 font-bold">
                       {market.outcomes[0].odds > 50 ? 'Bullish' : 'Bearish'}
                   </span>
              </div>
          </div>
      )}
    </div>
  );
};

export default AIAnalyst;
